// Generated by typings
// Source: https://raw.githubusercontent.com/types/npm-proxyquire/e94c99bbac8d350e28edd70471d9460a5534927b/lib/proxyquire.d.ts
declare module '~proxyquire/lib/proxyquire' {
function Proxyquire (): Proxyquire.Request;

module Proxyquire {
  interface Request {
    (module: string, stubs: any): any;
    <T> (module: string, stubs: any): T;

    load (module: string, stubs: any): any;
    load <T> (module: string, stubs: any): T;

    noCallThru(): Request;
    callThru(): Request;

    noPreserveCache(): void;
    preserveCache(): void;
  }
}

export = Proxyquire;
}
declare module 'proxyquire/lib/proxyquire' {
import main = require('~proxyquire/lib/proxyquire');
export = main;
}

// Generated by typings
// Source: https://raw.githubusercontent.com/types/npm-proxyquire/e94c99bbac8d350e28edd70471d9460a5534927b/index.d.ts
declare module 'proxyquire' {
import Proxyquire = require('~proxyquire/lib/proxyquire');

var proxyquire: Proxyquire.Request;

export = proxyquire;
}
